spring.application.name=rickandmorty-api
server.port=8080

# URL base da API externa
rickandmorty.api.base-url=https://rickandmortyapi.com/api

# Configuracao do cache Caffeine
# maximumSize: maximo de entradas | expireAfterWrite: expira em 10 minutos
spring.cache.caffeine.spec=maximumSize=500,expireAfterWrite=600s
spring.cache.type=
